name: PPT2VIDEO

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: FedericoCarboni/setup-ffmpeg@v3
        id: setup-ffmpeg

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: download binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ env.GITHUB_REPOSITORY }}
          LIBOPENH264: libopenh264-2.1.1-linux64.6.so.bz2
        run: |
          cd ppt2video/lib
          gh release download binary -p 'ffmpeg.bz2'
          bunzip2 ffmpeg.bz2
          chmod +x ffmpeg
          gh release download binary -p ${LIBOPENH264}
          bunzip2 ${LIBOPENH264}
          ln -s $(basename ${LIBOPENH264} .bz2) libopenh264.so.6
          LD_LIBRARY_PATH=. ./ffmpeg -version

      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm install
        run: |
          (cd ppt2video;npm install)

      - name: run ppt2video
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-1'
          PPT2VIDEO_OUTPUT_DIR: output
          PPT2VIDEO_TEMP_DIR: temp
        run: |
          mkdir $PPT2VIDEO_OUTPUT_DIR
          mkdir $PPT2VIDEO_TEMP_DIR
          node ppt2video/bin/ppt2video.js test/vuca.pptx

      - uses: actions/upload-artifact@v4
        with:
          name: vuca
          path: output
